# Development Environment Configuration for ToW MLOps

environment: development
cloud_provider: local
project_name: tow-research
version: 1.0.0

# Database Configuration
database:
  host: localhost
  port: 5432
  database: tow_experiments_dev
  username: tow_user
  password: dev_password
  ssl_mode: disable

# Model Server Configuration
model_server:
  host: 0.0.0.0
  port: 8000
  max_workers: 2
  timeout: 180
  max_batch_size: 4
  enable_batching: true
  enable_caching: false  # Disable for development
  rate_limit_per_minute: 50
  
  # Model settings
  max_sequence_length: 2048
  temperature: 0.7
  top_k: 50
  top_p: 0.95
  
  # Hardware optimization
  device: auto
  quantization: 4bit
  torch_compile: false
  flash_attention: false  # May not work on all dev machines

# Resource Configuration
resources:
  gpu_memory_fraction: 0.8
  cpu_cores: 4
  memory_limit_gb: 16
  
  # Auto-scaling
  min_replicas: 1
  max_replicas: 2
  target_cpu_percent: 80
  target_memory_percent: 85
  
  # Cost optimization
  use_spot_instances: false
  max_hourly_cost: 2.0
  auto_shutdown_idle_minutes: 15

# Monitoring Configuration
monitoring:
  metrics_port: 9090
  collection_interval: 30
  retention_days: 7
  
  # Performance thresholds (relaxed for dev)
  max_latency_ms: 10000
  min_throughput_rps: 0.5
  max_error_rate: 0.1
  min_confidence_score: 0.6
  
  # Alerts (disabled for dev)
  alert_on_high_latency: false
  alert_on_low_throughput: false
  alert_on_high_error_rate: true
  alert_on_model_drift: false
  alert_on_resource_usage: false

# Experiment Tracking Configuration
experiments:
  tracking_uri: sqlite:///mlruns_dev.db
  artifact_location: ./mlartifacts_dev
  
  # Wandb (optional for dev)
  wandb_project: tow-research-dev
  
  # Logging
  auto_log_model: true
  auto_log_metrics: true
  auto_log_artifacts: true
  log_system_metrics: false  # Reduce overhead in dev
  
  # Model versioning
  model_registry_name: ToW-Models-Dev

# Security Configuration
security:
  enable_auth: false  # Disabled for development
  enable_rate_limiting: false
  enable_cors: true
  allowed_origins: ["*"]
  
  # Model security
  enable_input_validation: true
  max_input_length: 5000
  sanitize_inputs: false  # For easier debugging
  
  # Network security
  enable_https: false

# Pipeline Configuration
pipeline:
  auto_trigger_training: false
  validation_split: 0.2
  early_stopping_patience: 3
  
  # Evaluation
  evaluation_datasets: ["mmlu_sample", "klue_sample"]
  evaluation_metrics: ["bleu", "rouge"]
  benchmark_threshold: 0.7
  
  # Deployment
  auto_deploy_on_improvement: false
  deployment_approval_required: false
  rollback_on_failure: true
  canary_deployment: false