# Production Environment Configuration for ToW MLOps

environment: production
cloud_provider: aws  # or gcp, azure
project_name: tow-research
version: 1.0.0

# Database Configuration
database:
  host: tow-prod-db.cluster-xyz.us-west-2.rds.amazonaws.com
  port: 5432
  database: tow_experiments_prod
  username: tow_prod_user
  # Password should be set via environment variable: DATABASE_PASSWORD
  ssl_mode: require

# Model Server Configuration
model_server:
  host: 0.0.0.0
  port: 8000
  max_workers: 8
  timeout: 300
  max_batch_size: 16
  enable_batching: true
  enable_caching: true
  cache_size: 5000
  rate_limit_per_minute: 200
  
  # Model settings
  max_sequence_length: 4096
  temperature: 0.7
  top_k: 50
  top_p: 0.95
  
  # Hardware optimization
  device: auto
  quantization: 4bit
  torch_compile: true
  flash_attention: true

# Resource Configuration
resources:
  gpu_memory_fraction: 0.95
  cpu_cores: 16
  memory_limit_gb: 64
  
  # Auto-scaling
  min_replicas: 2
  max_replicas: 20
  target_cpu_percent: 70
  target_memory_percent: 80
  scale_up_cooldown: 300
  scale_down_cooldown: 900
  
  # Cost optimization
  use_spot_instances: true
  max_hourly_cost: 50.0
  auto_shutdown_idle_minutes: 60

# Monitoring Configuration
monitoring:
  metrics_port: 9090
  collection_interval: 15
  retention_days: 90
  
  # Performance thresholds
  max_latency_ms: 3000
  min_throughput_rps: 5.0
  max_error_rate: 0.02
  min_confidence_score: 0.8
  
  # Alert channels (set via environment variables)
  # SLACK_WEBHOOK_URL, EMAIL_RECIPIENTS, DISCORD_WEBHOOK_URL
  
  # Alert conditions
  alert_on_high_latency: true
  alert_on_low_throughput: true
  alert_on_high_error_rate: true
  alert_on_model_drift: true
  alert_on_resource_usage: true

# Experiment Tracking Configuration
experiments:
  tracking_uri: mysql://tow_user:password@tow-mlflow-db.cluster-xyz.us-west-2.rds.amazonaws.com:3306/mlflow
  artifact_location: s3://tow-mlflow-artifacts-prod
  
  # Wandb
  wandb_project: tow-research-prod
  # WANDB_API_KEY set via environment variable
  
  # Logging
  auto_log_model: true
  auto_log_metrics: true
  auto_log_artifacts: true
  log_system_metrics: true
  
  # Model versioning
  model_registry_name: ToW-Models-Prod

# Security Configuration
security:
  enable_auth: true
  # JWT_SECRET set via environment variable
  jwt_expiry_hours: 24
  
  # API security
  enable_rate_limiting: true
  enable_cors: true
  allowed_origins: ["https://tow-ui.company.com", "https://api.company.com"]
  
  # Model security
  enable_input_validation: true
  max_input_length: 8192
  sanitize_inputs: true
  
  # Network security
  enable_https: true
  # SSL_CERT_PATH and SSL_KEY_PATH set via environment variables

# Pipeline Configuration
pipeline:
  auto_trigger_training: false  # Manual approval required
  training_schedule: "0 2 * * 0"  # Weekly at 2 AM Sunday
  validation_split: 0.15
  early_stopping_patience: 5
  
  # Evaluation
  evaluation_datasets: ["mmlu", "klue", "hellaswag", "arc", "truthfulqa"]
  evaluation_metrics: ["bleu", "rouge", "bertscore", "accuracy", "perplexity"]
  benchmark_threshold: 0.85
  
  # Deployment
  auto_deploy_on_improvement: false  # Manual approval required
  deployment_approval_required: true
  rollback_on_failure: true
  canary_deployment: true
  canary_traffic_percent: 5

# Production-specific settings
production_settings:
  # Load balancing
  load_balancer_strategy: weighted_round_robin
  health_check_interval: 30
  health_check_timeout: 10
  
  # Backup and recovery
  backup_schedule: "0 1 * * *"  # Daily at 1 AM
  backup_retention_days: 30
  disaster_recovery_enabled: true
  
  # Compliance
  enable_audit_logging: true
  gdpr_compliant: true
  hipaa_compliant: false
  
  # Performance optimization
  enable_model_caching: true
  enable_response_caching: true
  enable_preprocessing_cache: true
  cache_eviction_policy: lru
  
  # Monitoring integration
  datadog_integration: true
  newrelic_integration: false
  grafana_dashboard: true
  prometheus_metrics: true